services:
  app:
    build: .
    ports:
      - "4050:5000"
    environment:
      - NODE_ENV=production
      - PORT=4050
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
